### ISSUE TITLE
make deleteFiles function not delete ogg/images that are associated with other srtb files

### ISSUE THREAD

**Issue by jy1263** [AndreasWebdev/spinshare-client#21]

**Comment by AndreasWebdev** [comment]
why not?

**Comment by jy1263** [comment]
i was thinking if there are two srtb files that use the same ogg/image, when one srtb file is deleted along with those files, the other srtb wont hav it's required assets

**Comment by AndreasWebdev** [comment]
That is as intended, the confirm dialog will show you which files will be deleted. It also only affects manually installed songs.

**Comment by jy1263** [comment]
o yea thats true thx
