### ISSUE TITLE
Korean is just straight up broken...

### ISSUE THREAD

**Issue by AndreasWebdev** [AndreasWebdev/spinshare-client#26]
![image](https://user-images.githubusercontent.com/7365286/79401215-cd9b2c80-7f88-11ea-9078-f975f9ebc23f.png)

**Comment by SeeBeyondDev** [comment]
perhaps an error with character encoding? although the site meta is set to utf8

**Comment by AndreasWebdev** [comment]
I think it's just the font not supporting korean characters
