### ISSUE TITLE
Show Available Difficulties

### ISSUE THREAD

**Issue by AndreasWebdev** [AndreasWebdev/spinshare-client#7]
Needs API updates as well

**Comment by jy1263** [comment]
Here are the numbers associated with each difficulty in the .srtb file:
Easy is ```\"difficulties\":[{\"bundle\":\"CUSTOM\",\"assetName\":\"TrackData_0\",\"_difficulty\":2,\"_compatibilityVersion\":0}]```
Normal is ```difficulties\":[{\"bundle\":\"CUSTOM\",\"assetName\":\"TrackData_0\",\"_difficulty\":3,\"_compatibilityVersion\":0}]```
Hard is ```\"difficulties\":[{\"bundle\":\"CUSTOM\",\"assetName\":\"TrackData_0\",\"_difficulty\":4,\"_compatibilityVersion\":0}]```
Expert is ```\"difficulties\":[{\"bundle\":\"CUSTOM\",\"assetName\":\"TrackData_0\",\"_difficulty\":5,\"_compatibilityVersion\":0}]```
XD is ```\"difficulties\":[{\"bundle\":\"CUSTOM\",\"assetName\":\"TrackData_0\",\"_difficulty\":6,\"_compatibilityVersion\":0}]```

**Comment by jy1263** [comment]
When it has multiple difficulties, it's stringed together like ```\"difficulties\":[{\"bundle\":\"CUSTOM\",\"assetName\":\"TrackData_0\",\"_difficulty\":2,\"_compatibilityVersion\":0},{\"bundle\":\"CUSTOM\",\"assetName\":\"TrackData_1\",\"_difficulty\":3,\"_compatibilityVersion\":0},{\"bundle\":\"CUSTOM\",\"assetName\":\"TrackData_2\",\"_difficulty\":4,\"_compatibilityVersion\":0}]```

**Comment by AndreasWebdev** [comment]
I know, just need to implement that on the server side. I'll do that tomorrow, though.. too late :D

**Comment by jy1263** [comment]
o okie lol
thx for all the hard work and progress on this tho, i'm rlly excited for launch
